name: tests

on:
    push:
        branches:
            - develop
            - main
    pull_request:
        types:
            - opened
            - synchronize
            - reopened
            - ready_for_review
        branches:
            - develop
            - main

permissions:
    contents: read

jobs:
    ci:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout code
                uses: actions/checkout@v7
                with:
                    persist-credentials: false

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.4'
                    tools: composer:v2
                    coverage: none

            -   name: Setup Node
                uses: actions/setup-node@v7
                with:
                    node-version: '22'

            -   name: Setup Application
                run: composer setup

            -   name: Start Laravel Server
                run: composer run dev > /dev/null 2>&1 &

            -   name: Wait for Server
                run: |
                    for i in {1..30}; do
                      curl -s http://127.0.0.1:8000 && break
                      sleep 1
                    done

            -   name: Run CI Checks
                run: composer ci:check
